apiVersion: v2
name: ps-app
description: A Helm chart for Pluralsight with Redis and PostgreSQL
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: redis
    version: "18.x.x"
    repository: https://charts.bitnami.com/bitnami
  
  - name: postgresql
    version: "13.x.x"
    repository: https://charts.bitnami.com/bitnami